### ISSUE TITLE
Feature Request: custom request based labels

### ISSUE THREAD

**Issue by mman** [joao-fontenele/express-prometheus-middleware#21]
Hi @joao-fontenele,

Thanks for your great library, works like a charm for monitoring my node+express based backed api servers.

I was thinking how to make the monitoring even better, and I think I have a suggestion.

My HTTP requests contain various useful headers, like user agent, client sdk version, app version, etc.

I think it would be great to have a mechanism where these can be somehow processed via a hook that inputs a request and outputs a set of additional labels to attach to the request and duration metrics.

I can try to hook up a PR if you are interested.

Thanks,
Martin

**Comment by joao-fontenele** [comment]
hello @mman 

it looks line an interesting feature. If you can, I would gladly accept a PR

**Comment by orinciog** [comment]
@mman 
Hi,

I've created a PR for this feature request. See: https://github.com/joao-fontenele/express-prometheus-middleware/pull/25.

Sorry if you already begun the work to this feature, but I needed this feature ASAP.
