### ISSUE TITLE
Prom Client missing when updating to latest version

### ISSUE THREAD

**Issue by lehno** [joao-fontenele/express-prometheus-middleware#32]
Error: Cannot find module 'prom-client'

**Comment by joao-fontenele** [comment]
hello @lehno, there were a breaking change, to fix issue #22 , it's documented how to migrate on [v0.9.0 changelog](https://github.com/joao-fontenele/express-prometheus-middleware/compare/v0.8.5...v0.9.0)

If it does not solve the issue, please reopen with more details
