### ISSUE TITLE
How to expose only in secondary app?

### ISSUE THREAD

**Issue by lehno** [joao-fontenele/express-prometheus-middleware#33]
I have my main express app and I'm passing a new express app that listens in another port only for Prometheus inside my Kubernetes cluster.

![image](https://user-images.githubusercontent.com/5764569/82689746-e2877180-9c52-11ea-90d1-ab096d47436d.png)

But if I call my main application /metrics, it also returns the metrics.
I want to expose only on port 9090 in the secondary app.

**Comment by joao-fontenele** [comment]
Hello, I never tried this, but express works based on middlewares. So if you put a `/metrics` route handler that responds, say `Not Found`, before the prometheus middleware, you would achieve this
