### ISSUE TITLE
Disable normalization of status codes 

### ISSUE THREAD

**Issue by lkreimann** [joao-fontenele/express-prometheus-middleware#34]
Hello all, is there a way to disable the normalization of status codes. I'd rather have 200, 401, 404, ... etc. if that's possible. I tried some things and looked at the code but I didn't find anything. Can someone help me with this?

**Comment by joao-fontenele** [comment]
Hi, as of now, there's no way to disable the feature

I don't know of your use case, but note that this normalization, is to avoid growth of the metrics dimensionality. Meaning if it's disabled you will end up putting more load into prometheus.

In any case, I would review a PR implementing this feature too.

**Comment by lkreimann** [comment]
You're making a good point here. It's probably better to leave it like that, we had problems with too much load on our Prometheus operator, so we shouldn't put more data out there than needed.

Thanks for your response! I'm going to close the issue.
