### ISSUE TITLE
Argument Chunk error 

### ISSUE THREAD

**Issue by johannb75** [joao-fontenele/express-prometheus-middleware#47]
Hi,
I implemented this library in my express app:
```ts
import promMid from 'express-prometheus-middleware';
const app = express();
app.use(
    promMid({
      collectDefaultMetrics: true,
      collectGCMetrics: true,
    })
);
```

The server starts without any problem but when I go on the `/metrics` route, this error appears in my console:

>  UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Promise
    at ServerResponse.end (_http_outgoing.js:759:13)
    at C:\nodejs\wavychat-expo\back-end\node_modules\express-prometheus-middleware\src\index.js:125:16
    at Layer.handle [as handle_request] (C:\nodejs\wavychat-expo\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\nodejs\wavychat-expo\back-end\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\nodejs\wavychat-expo\back-end\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\nodejs\wavychat-expo\back-end\node_modules\express\lib\router\layer.js:95:5)
    at C:\nodejs\wavychat-expo\back-end\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\nodejs\wavychat-expo\back-end\node_modules\express\lib\router\index.js:335:12)
    at next (C:\nodejs\wavychat-expo\back-end\node_modules\express\lib\router\index.js:275:10)
    at responseTime (C:\nodejs\wavychat-expo\back-end\node_modules\response-time\index.js:61:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks in advance

**Comment by bkbwese** [comment]
I was getting this same problem this morning. Dug into it a bit, looks like it's because the prom-client was updated in version 13 to return a promise instead of a string for the function call registry.metrics().

@johannb75 if you downgrade to version 12.0.0 of prom-client, that will likely fix your problem.

As for a permanent fix, calls to prom client need to now have an await, as noted in the release notes:
https://github.com/siimon/prom-client/releases/tag/v13.0.0

**Comment by bkbwese** [comment]
Side note: I ran into this problem as a result of accidentally installing version 13 of prom-client. Installing dependencies correctly should avoid this.

**Comment by AAverin** [comment]
If you end up here confused why your `collect` function in `prom-client` is not working, it's a feature of v13 of prom-client.
So if you downgraded to v12 because of this issue, don't use point in time collection in gauges
