### ISSUE TITLE
Define Custom Metrics?

### ISSUE THREAD

**Issue by jconallen** [joao-fontenele/express-prometheus-middleware#52]
Is it possible to define (and provide) custom metrics?

**Comment by joao-fontenele-daitan** [comment]
hello @jconallen , yes it's possible. Just define and use the custom metrics outside of the lib normally. You just wont need to define an endpoint exposing the metrics, because it's already done in the lib

**Comment by jconallen** [comment]
I am relatively new this  and this component.  Can you provide a short (minimal) example?
