### ISSUE TITLE
npm audit high vulnerability

### ISSUE THREAD

**Issue by shlomo-artlist** [joao-fontenele/express-prometheus-middleware#61]
Hi
There's an NPM audit high vulnerability in version 1.2.0

Versions:
node: v14.16.1
npm: 7.20.5

npm audit:

```
# npm audit report

ini  <1.3.6
Prototype Pollution - https://npmjs.com/advisories/1589
fix available via `npm audit fix`
node_modules/gc-stats/node_modules/ini

minimist  <0.2.1 || >=1.0.0 <1.2.3
Prototype Pollution - https://npmjs.com/advisories/1179
fix available via `npm audit fix`
node_modules/gc-stats/node_modules/minimist
node_modules/gc-stats/node_modules/rc/node_modules/minimist
  mkdirp  0.4.1 - 0.5.1
  Depends on vulnerable versions of minimist
  node_modules/gc-stats/node_modules/mkdirp

tar  <=3.2.2 || 4.0.0 - 4.4.14 || 5.0.0 - 5.0.6 || 6.0.0 - 6.1.1
Severity: high
Arbitrary File Creation/Overwrite due to insufficient absolute path sanitization - https://npmjs.com/advisories/1770
Arbitrary File Creation/Overwrite via insufficient symlink protection due to directory cache poisoning - https://npmjs.com/advisories/1771
fix available via `npm audit fix`
node_modules/gc-stats/node_modules/tar

4 vulnerabilities (3 low, 1 high)
```

npm ls tar:
```
@common/prometheus@1.0.0 /Users/shlomohal/Develop/core.common.modules/prometheus
└─┬ express-prometheus-middleware@1.2.0
  └─┬ prometheus-gc-stats@0.6.3
    └─┬ gc-stats@1.4.0
      └─┬ node-pre-gyp@0.13.0
        └── tar@4.4.8
```

I see there's a PR from @dependabot:
https://github.com/joao-fontenele/express-prometheus-middleware/pull/60

Can you merge it please?

**Comment by joao-fontenele-daitan** [comment]
I can merge later, but rest assured that any lock files in this project is ignored once you install this dependency in your project, so you should audit fix in your project only

> The difference is that package-lock.json cannot be published, and it will be ignored if found in any place other than the root project.

from: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson

**Comment by joao-fontenele** [comment]
I can merge later, but rest assured that any lock files in this project is ignored once you install this dependency in your project, so you should audit fix in your project only

> The difference is that package-lock.json cannot be published, and it will be ignored if found in any place other than the root project.

from: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson

**Comment by shlomo-artlist** [comment]
Oh, wait - you're right.
So how come I see this issue and can't fix it via `npm audit fix`?
